sudo: required
dist: trusty
language: generic

addons:
  apt:
    sources:
    - hvr-ghc
    - sourceline: 'ppa:hvr/ghcjs'
    - ubuntu-toolchain-r-test
    - sourceline: 'deb https://deb.nodesource.com/node_10.x trusty main'
      key_url: 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key'
    packages:
    - cabal-install-2.2
    - ghcjs-8.2
    - gcc-6

cache:
  bundler: false
  directories:
  - $HOME/.ghc/
  - $HOME/.ghcjs/
  - $HOME/.cabal/bin
  - $HOME/.cabal/share
  - $HOME/.cabal/lib
  - $HOME/.cabal/libexec

before_install:
    - export PATH=$HOME/.cabal/bin:$PATH
    - export PATH=/opt/cabal/2.2/bin:$PATH
    - export PATH=/opt/alex/3.1.4/bin:$PATH
    - export PATH=/opt/happy/1.19.5/bin:$PATH
    - export PATH=/opt/ghcjs/8.2/bin:$PATH
    - export PATH=$TRAVIS_BUILD_DIR/node_modules/.bin:$PATH
    - du -sh $HOME/.ghcjs $HOME/.ghc $HOME/.cabal/bin $HOME/.cabal/lib $HOME/.cabal/share
    - rm -f ~/.cabal/config
    - cabal update # to ensure the config exists
    - 'fgrep hackage-ghcjs-overlay.nomeata.de/ $HOME/.cabal/config ||
      echo -e "repository ghcjs-overlay\n url: http://hackage-ghcjs-overlay.nomeata.de/\n secure: True\n root-keys:\n key-threshold: 0" >> ~/.cabal/config'
    - cat ~/.cabal/config
    - cabal update

install:
    # lets see what we will do
    - cabal install --dry-run -j1 --ghcjs -w ghcjs-8.2 --dependencies-only --disable-tests --constraint="primitive < 0.6.4.0"
    # lets do it (and do not fail here, so that partial builds still warm the cache)
    - cabal install -j1 --ghcjs -w ghcjs-8.2 --dependencies-only --disable-tests --constraint="primitive < 0.6.4.0" || true

jobs:
  include:
   - stage: warm cache with program dependencies
     if: type = api
     script:
       # dont actually build, we just want to warm the cache
       - ghcjs-pkg list

   - stage: build, test and deploy
     script:
       # now build
       - cabal configure --distdir=dist-ghcjs --ghcjs -w ghcjs-8.2 --disable-library-profiling
       - cabal build     --distdir=dist-ghcjs
       - cabal haddock   --distdir=dist-ghcjs --executables --internal --hyperlink-source
       - cp -vr dist-ghcjs/build/*/*.jsexe gh-page
       - cp -vr dist-ghcjs/doc/html/*/* gh-page/doc

     deploy:
       provider: pages
       local-dir: gh-page
       # fqdn: domain.de
       keep-history: true
       allow-empty-commit: true
       skip-cleanup: true
       github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
       on:
         branch: master

before_cache:
  - rm -rf $HOME/.ghcjs/*/ghcjs/ghcjs-boot/
  - du -sh $HOME/.ghcjs $HOME/.ghc $HOME/.cabal/bin $HOME/.cabal/lib $HOME/.cabal/config $HOME/.cabal/share

